#!/bin/bash
#SBATCH -A 122792648842
#SBATCH --job-name=test
#SBATCH --output=3d_class_001.%j
#SBATCH --time=96:00:00
#SBATCH --ntasks=3                  # Relion needs 1 master (CPU) and several slaves (GPU)
#SBATCH --nodes=2                   # 2 GPU slaves
#SBATCH --cpus-per-task=1           # More CPU might help GPU, but at additional charge
#SBATCH --mem=110G                  # Maximum is 114688 MB for the 128 GB nodes
#SBATCH -p gpu
#SBATCH --gres=gpu:1                # 1 GPU per node

source ~/.bashrc

source ~/.p3relion3

mkdir -p Refine3D/3d_class_001

mpirun -n 3 `which relion_refine_mpi` --o Class3D/3d_class_001/run --i particles.star --particle_diameter 300 --angpix 3.74 --ref ref/init.mrc --firstiter_cc --ini_high 60 --ctf --ctf_corrected_ref --iter 50 --tau2_fudge 4 --K 3 --flatten_solvent --zero_mask --oversampling 1 --healpix_order 2 --offset_range 5 --offset_step 2 --sym C1 --norm --scale  --j 1 --dont_check_norm --no_parallel_disc_io --gpu &> 3d_auto_001.log
