#!/bin/bash
#SBATCH -A 122792648842
#SBATCH --job-name=test
#SBATCH --output=jobs/ex_ptcl_001.%j
#SBATCH --time=24:00:00
#SBATCH --ntasks=28                 # Each node on terra has 28 CPU
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1           # More CPU might help GPU, but at additional charge
#SBATCH --mem=10G                   # Maximum is 57344 MB for the 64 GB nodes

source ~/.bashrc

source ~/.p3relion1

# Use the following line to generate micrographs_ctf.star
#relion_run_ctffind --i "Micrographs/*/*DW.mrc" --only_make_star

mpirun -n 28 `which relion_preprocess_mpi` --o particles --mic_star micrographs_ctf.star --coord_suffix _automatch.star --extract --extract_size 200 --scale 100 --norm --bg_radius 40 --white_dust -1 --black_dust -1 --invert_contrast &>ex-ptcl.log
# bg_radius = particle_diameter_in_Angstrom / Apix / 2 / (extract_size / scale)
